### ISSUE TITLE
Read fods

### ISSUE THREAD

**Issue by retorquere** [iuvbio/pandas_ods_reader#2]
Can this library be extended to read fods (flat ods) files?

**Comment by iuvbio** [comment]
Should be possible, yes. I will take a look once I'm back from vacation.

**Comment by iuvbio** [comment]
@retorquere .fods files are supported now. Nothing about the API has changed, the `read_ods` function chooses the parser based on the file extension.

Since the test files are quite simple, there might be some problems with more complex files. Please make a new issue for any bugs you might find.
