### ISSUE TITLE
Improve error from invalid path

### ISSUE THREAD

**Issue by denisvitez** [iuvbio/pandas_ods_reader#5]
Hi,

I tried to use this project inside my application, but I am unable to get even the most basic example to work:
```
from pandas_ods_reader import read_ods

path = "home/test/example1.ods"
df = read_ods(path)
```

The error that gets thrown is:
`KeyError: '.ods'`  inside `ezodf/document.py", line 69, in __detect_mime_type`

Looking at the `ezodf` code, I am not sure how this is ever able to work:

The code in question is:
```
ext = os.path.splitext(file_manager.zipname)[1]
mime_type = MIMETYPES[ext]
```

And if we look into the MIMETYPES:
```
MIMETYPES = {
    'odt': "application/vnd.oasis.opendocument.text",
    'ott': "application/vnd.oasis.opendocument.text-template",
    'odg': "application/vnd.oasis.opendocument.graphics",
    'otg': "application/vnd.oasis.opendocument.graphics-template",
    'odp': "application/vnd.oasis.opendocument.presentation",
    'otp': "application/vnd.oasis.opendocument.presentation-template",
    'ods': "application/vnd.oasis.opendocument.spreadsheet",
    'ots': "application/vnd.oasis.opendocument.spreadsheet-template",
    'odc': "application/vnd.oasis.opendocument.chart",
    'otc': "application/vnd.oasis.opendocument.chart-template",
    'odi': "application/vnd.oasis.opendocument.image",
    'oti': "application/vnd.oasis.opendocument.image-template",
    'odf': "application/vnd.oasis.opendocument.formula",
    'otf': "application/vnd.oasis.opendocument.formula-template",
    'odm': "application/vnd.oasis.opendocument.text-master",
    'oth': "application/vnd.oasis.opendocument.text-web",
}
```
So the .splittext method returns the extension with the . included (.ods), but the keys are without the comma. But this would mean that the library would never work, so I'm guessing I'm just missing something basic?

**Comment by denisvitez** [comment]
I was using an absolute path without the leading /, but the error made me overlook it.

**Comment by ljnsn** [comment]
Thanks for the suggestion, I will reopen this issue to remind myself to improve the error message :)
